name: flappy_dash_adventures
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.6
  flame: 1.18.0
  flame_audio: 2.10.1
  flutter_gen_runner: 5.5.0+1
  easy_debounce: ^2.0.3
  gamepads:
    git:
      url: https://github.com/flame-engine/gamepads.git
      ref: main
      path: packages/gamepads
  flame_bloc: 1.12.0
  freezed: 2.5.2
  json_serializable: 6.8.0
  shared_preferences: 2.2.3
  flutter_bloc: ^8.1.2

dev_dependencies:
  build_runner: 2.4.9
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.0

flutter_gen:
  output: lib/utils/
  assets:
    outputs:
      class_name: Assets

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/sprites/

